### ISSUE TITLE
 supplementary material request

### ISSUE THREAD

**Issue by zhenggang65** [jhonygiraldo/GraphMOS#1]
Hi, thanks for your amazing work, I am reading your paper on the IEEE [website](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9288631) now and note that Appendix A - E is not in the paper as you mentioned in the paper. I wonder if I have read the wrong place, or if not can you tell me where can we access those appendices.  Many thanks.

**Comment by jhonygiraldo** [comment]
Hi @zhenggang65, thank you for your interest in my research. You can find the supplementary material at the end of the IEEE [website](https://ieeexplore.ieee.org/document/9288631) in [media](https://ieeexplore.ieee.org/document/9288631/media#media). You can also always find all my preprints and my research material in my [Personal Webpage](https://sites.google.com/view/jhonygiraldo) in [Publications](https://sites.google.com/view/jhonygiraldo/publications?authuser=0). I hope that helps.
Best,
Jhony.

**Comment by jhonygiraldo** [comment]
[Link Supplementary Material](https://drive.google.com/file/d/1Cu0Al-SWUw9IqHGmQfd8ysDxG_SW8Vhj/view?usp=sharing)
